/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.3.0.109 */
/* Module Version: 5.6 */
/* Fri Dec 12 23:47:21 2014 */

/* parameterized module instance */
capture_pll __ (.CLKI( ), .RESETC( ), .CLKOP( ), .CLKOS2( ));
