/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.3.0.109 */
/* Module Version: 5.6 */
/* Tue Dec 09 17:39:41 2014 */

/* parameterized module instance */
pll __ (.CLKI( ), .CLKOP( ));
