/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.3.0.109 */
/* Module Version: 5.6 */
/* Thu Dec 11 01:02:38 2014 */

/* parameterized module instance */
vga_pll __ (.CLKI( ), .CLKOP( ));
